### ISSUE TITLE
data frame creation error

### ISSUE THREAD

**Issue by natesayles** [DerekYves/rsurveygizmo#1]
I was wondering if you could clarify an error for me? I am following the instructions that you have provided and double checked if I have the correct secret API key/survey id. The package installs without problem. However, when I use either the pullsg or pullsg_campaign, I get this error message:

" Error in `$<-.data.frame`(`*tmp*`, "qtext", value = "_ID") : 
  replacement has 1 row, data has 0 
4 stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
    "replacement has %d rows, data has %d"), N, nrows), domain = NA) 
3 `$<-.data.frame`(`*tmp*`, "qtext", value = "_ID") 
2 `$<-`(`*tmp*`, "qtext", value = "_ID") 
1 pullsg(2730460, api, completes_only = T) "

**Comment by DerekYves** [comment]
Hi there. It sounds like there may be an issue with question aliases. Do you have those set up for your questions on Survey gizmo? Ideally you have them set up for all questions. Let me know if this fixes the issue. Could you also send the command you're using sans the API key?

**Comment by natesayles** [comment]
Yes each question has a unique alias. I also figured out what the issue that I was using the api secret key to instead of the api key lol, completely my mistake. Thanks for getting back to me so quickly though. Great R package!

**Comment by natesayles** [comment]
I have a follow up question about pulling SPSS variable names along with the alias titles. Where/What would be the best way to implement this into your code?

**Comment by DerekYves** [comment]
Hi Nate,

I don't see anything in the docs which suggest that the SPSS variable names
can be downloaded by the user API. You might want to reach out to them to
see if this is possible. If so it would be another response object like the
aliases, and would then need to be merged in using the question id.

This is the part of the code where the names are merged in after cleaning:

# Left join of the cleaned name table

lc_names <- merge(lc_names, lc_qs, by="id", all.x=T)
lc_names <- lc_names[order(lc_names$index),]
rownames(lc_names) <- NULL # reset the row.names attribute

# Replace variable name with shortname wher available

lc_names$id   <- ifelse(is.na(lc_names$shortname),
lc_names$id, lc_names$shortname)

# Subset the vector of cleaned names and replace the full_set names

lc_names <- lc_names[,'id']
colnames(lc_fullset) <- lc_names
